import { Sparkles, ChefHat, Save, ThumbsDown } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import { useParams } from "react-router-dom";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { socket } from "@/lib/socket";
import { useDispatch, useSelector } from "react-redux";
import type { RootState } from "@/store/store";
import {
  setRecipe,
  clearRecipe,
  setSavedRecipes,
  appendSavedRecipes,
  addSavedRecipe,
} from "@/store/slices/recipeSlice";
import {
  generateRecipeApi,
  getSavedRecipesApi,
  saveRecipeApi,
} from "@/api/recipe/recipe.api";
import { Badge } from "../ui/badge";

export default function RecipeDisplay() {
  const { roomId } = useParams();
  const dispatch = useDispatch();

  const currentRecipe = useSelector(
    (state: RootState) => state.recipe.currentRecipe,
  );
  const ingredient = useSelector((state: RootState) => state.recipe.ingredient);
  const savedRecipes =
    useSelector((state: RootState) => state.recipe.savedRecipes) || [];
  const page = useSelector((state: RootState) => state.recipe.page);
  const hasMore = useSelector((state: RootState) => state.recipe.hasMore);

  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);

  // FETCH PAGINATED SAVED RECIPES
  const fetchSavedRecipes = async (pageNumber = 1) => {
    try {
      if (!roomId) return;

      const data = await getSavedRecipesApi(roomId, pageNumber, 5);
      const normalizedRecipes = data.data.recipes.map((r: any) => ({
        id: r._id,
        recipe: r.recipeText,
        ingredients: r.ingredients,
        createdAt: r.createdAt,
      }));

      if (pageNumber === 1) {
        dispatch(setSavedRecipes(normalizedRecipes));
      } else {
        dispatch(appendSavedRecipes(normalizedRecipes));
      }
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    if (!roomId) return;
    fetchSavedRecipes(1);
  }, [roomId]);

  const handleScroll = (e: any) => {
    if (e.target.scrollTop === 0 && hasMore) {
      fetchSavedRecipes(page + 1);
    }
  };

  useEffect(() => {
    const handleRecipeGenerated = (data: {
      recipe: string;
      ingredients: string[];
      generatedBy: string;
    }) => {
      console.log(data.ingredients)
      dispatch(
        setRecipe({
          recipe: data.recipe,
          ingredient: data.ingredients,
        }),
      );
      toast.success(`Recipe generated by ${data.generatedBy}(Admin)`);
    };

    const handleRecipeSaved = (data: {
      recipe: string;
      ingredients: string[];
    }) => {
      dispatch(
        addSavedRecipe({
          recipe: data.recipe,
          ingredients: data.ingredients,
          createdAt: new Date().toISOString(),
        }),
      );

      dispatch(clearRecipe());
      toast.success(`Recipe saved!!`);
    };

    const handleRecipeCleared = () => {
      dispatch(clearRecipe());
      toast("Recipe cleared");
    };

    socket.on("recipe_generated", handleRecipeGenerated);
    socket.on("recipe_saved", handleRecipeSaved);
    socket.on("recipe_cleared", handleRecipeCleared);

    return () => {
      socket.off("recipe_generated", handleRecipeGenerated);
      socket.off("recipe_saved", handleRecipeSaved);
      socket.off("recipe_cleared", handleRecipeCleared);
    };
  }, [dispatch]);

  const handleGenerateRecipe = async () => {
    try {
      if (!roomId) {
        toast.error("Invalid room");
        return;
      }
      setLoading(true);

      await generateRecipeApi(roomId);
    } catch (err: any) {
      if (err.status === 401) {
        toast.error("Session expired. Please login again");
        return;
      }
      toast.error(err.message || "Failed to generate recipe");
    } finally {
      setLoading(false);
    }
  };

  const handleSaveRecipe = async () => {
    try {
      if (!roomId) {
        toast.error("Invalid room");
        return;
      }

      if (!currentRecipe) {
        toast.error("No recipe to save");
        return;
      }
      setSaving(true);
      await saveRecipeApi(roomId, currentRecipe, ingredient);
    } catch (err: any) {
      if (err.status === 401) {
        toast.error("Session expired. Please login again");
        return;
      }
      toast.error(err.message || "Failed to save recipe");
    } finally {
      setSaving(false);
    }
  };

  const handleDislike = () => {
    if (!roomId) return;

    socket.emit("dislike_recipe", { roomId });
  };

  return (
    <div className="space-y-6">
      {/* GENERATE */}
      <div className="flex justify-center">
        <Button
          size="lg"
          className="rounded-full px-10 shadow-lg"
          onClick={handleGenerateRecipe}
          disabled={loading}
        >
          <Sparkles className="mr-2 h-4 w-4" />
          {loading ? "Generating..." : "Generate Recipe"}
        </Button>
      </div>

      {/* CARD */}
      <Card className="min-h-[300px] shadow-sm overflow-hidden">
        <CardHeader className="flex flex-row items-center justify-between border-b">
          <CardTitle className="flex items-center gap-2 text-sm font-semibold">
            Gemini Kitchen Intelligence
          </CardTitle>
          <ChefHat className="h-5 w-5 text-primary" />
        </CardHeader>

        <Separator />

        <CardContent className="p-6 space-y-4">
          {currentRecipe ? (
            <>
              {/* INGREDIENTS */}
              <div>
                <h3 className="font-semibold text-sm mb-2">
                  Ingredients Used:
                </h3>
                {ingredient?.length > 0 ? (
                  <div className="flex flex-wrap gap-2">
                    {ingredient.map((item) => (
                      <Badge key={item}>{item?.trim() || "N/A"}</Badge>
                    ))}
                  </div>
                ) : (
                  <p className="text-xs text-muted-foreground">
                    No ingredients found
                  </p>
                )}
              </div>

              <Separator />

              {/* RECIPE */}
              <div>
                <h3 className="font-semibold text-sm mb-2">Recipe:</h3>
                <p className="text-sm whitespace-pre-line">{currentRecipe}</p>
              </div>

              {/* ACTION BUTTONS */}
              <div className="flex gap-3 pt-4">
                <Button
                  onClick={handleSaveRecipe}
                  disabled={saving}
                  className="flex-1"
                >
                  <Save className="mr-2 h-4 w-4" />
                  {saving ? "Saving..." : "Save"}
                </Button>

                <Button
                  variant="destructive"
                  onClick={handleDislike}
                  className="flex-1"
                >
                  <ThumbsDown className="mr-2 h-4 w-4" />
                  Dislike
                </Button>
              </div>
            </>
          ) : (
            <p className="text-sm text-muted-foreground italic text-center">
              No recipe generated yet...
            </p>
          )}
        </CardContent>
      </Card>
      {/* SAVED RECIPES (SCROLLABLE) */}
      <div
        className="max-h-[400px] overflow-y-auto space-y-4"
        onScroll={handleScroll}
      >
        {savedRecipes?.length > 0 &&
          savedRecipes.map((item, index) => (
            <Card key={index} className="p-4">
              <p className="text-sm whitespace-pre-line">
                {item?.recipe || "No recipe"}
              </p>

              <div className="flex flex-wrap gap-2 mt-2">
                {(item?.ingredients || []).map((ing, i) => (
                  <Badge key={i}>{ing}</Badge>
                ))}
              </div>
            </Card>
          ))}
      </div>
    </div>
  );
}
